// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HealthStatus struct {
	Status  int32  `json:"status"`
	Message string `json:"message"`
}

type Mutation struct {
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}

type UserResponse struct {
	Message string  `json:"message"`
	Token   *string `json:"token,omitempty"`
}
